---
- hosts: all
  become: True
  tasks:

  - name: echo cat message
    copy:
       content: Ansible managed node by erwin
       dest: /home/erwin/motd

  - name: create user
    user:
      name: erwin
      state: present
